on: [push]
name: test
jobs:
  runhaskell:
    name: Run Tests
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
      - uses: freckle/stack-cache-action@main
      - run: stack test --coverage